name: GA_EX_01
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v5
            - name: Install NodeJS
              uses: actions/setup-node@v5
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run fix
              run: npm run lint
            - name: Run test
              run: npm test